# Generated by Django 5.1.7 on 2025-03-19 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_apply_living_remove_schedule_apply_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='ApplyYourself',
        ),
        migrations.AddField(
            model_name='apply',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
    ]
