# Generated by Django 5.1.7 on 2025-03-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_schedule_applyyourself_apply_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='Living',
        ),
        migrations.AddField(
            model_name='living',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
    ]
