# Generated by Django 5.1.7 on 2025-03-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_schedule_living_living_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='bible_reading',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='chairman',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_prayer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_song',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='living_song',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_prayer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_song',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='treasures_speaker',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='treasures_spiritual_gems_speaker',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='treasures_spiritual_gems_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='treasures_talk_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
