# Generated by Django 5.1.7 on 2025-03-19 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_schedule_bible_reading_alter_schedule_chairman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='living',
            name='living_talk_duration',
        ),
        migrations.RemoveField(
            model_name='living',
            name='living_talk_speaker',
        ),
        migrations.RemoveField(
            model_name='living',
            name='living_talk_title',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='bible_reading',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='chairman',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='closing_prayer',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='closing_song',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='opening_prayer',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='opening_song',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='treasures_speaker',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='treasures_spiritual_gems_speaker',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='treasures_spiritual_gems_title',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='treasures_talk_title',
        ),
        migrations.AddField(
            model_name='living',
            name='section',
            field=models.CharField(default='Talk', max_length=255),
        ),
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_song', models.CharField(max_length=255, null=True)),
                ('closing_prayer', models.CharField(max_length=255, null=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='LivingTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.living')),
            ],
        ),
        migrations.CreateModel(
            name='LivingTalkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=255, null=True)),
                ('duration', models.CharField(max_length=255, null=True)),
                ('living_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='schedule.livingtalk')),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_song', models.CharField(max_length=255, null=True)),
                ('opening_prayer', models.CharField(max_length=255, null=True)),
                ('chairman', models.CharField(max_length=255, null=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Treasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_reading', models.CharField(max_length=255, null=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TreasuresTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('treasure', models.ForeignKey(default='Talk', on_delete=django.db.models.deletion.CASCADE, to='schedule.treasures')),
            ],
        ),
        migrations.CreateModel(
            name='TalkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=255, null=True)),
                ('duration', models.CharField(max_length=255, null=True)),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.treasurestalk')),
            ],
        ),
    ]
