# Generated by Django 5.1.7 on 2025-03-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_rename_treasure_treasurestalk_treasure_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='apply_part',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='living_song',
        ),
        migrations.AddField(
            model_name='living',
            name='living_song',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ApplyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_part', models.CharField(max_length=255)),
                ('apply_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.apply')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.applypart')),
            ],
        ),
    ]
