# Generated by Django 5.1.7 on 2025-03-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_apply_apply_part_remove_schedule_living_song_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='apply_duration',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='apply_student',
        ),
    ]
