# Generated by Django 5.1.7 on 2025-03-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_biblestudy_biblestudyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='living',
            name='section',
        ),
    ]
