# Generated by Django 5.1.7 on 2025-03-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_remove_living_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biblestudyinfo',
            old_name='living_session',
            new_name='living_section',
        ),
        migrations.RenameField(
            model_name='livingtalkinfo',
            old_name='living_session',
            new_name='living_section',
        ),
        migrations.CreateModel(
            name='TreasuresTalkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=255, null=True)),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.treasurestalk')),
            ],
        ),
        migrations.DeleteModel(
            name='TalkInfo',
        ),
    ]
