# Generated by Django 5.1.7 on 2025-03-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_rename_living_session_biblestudyinfo_living_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
