# Generated by Django 5.1.7 on 2025-03-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='week',
        ),
    ]
