# Generated by Django 5.1.7 on 2025-03-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_remove_schedule_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='bible_study_conductor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='bible_study_reader',
        ),
        migrations.AddField(
            model_name='schedule',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
