# Generated by Django 5.1.7 on 2025-03-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_remove_schedule_bible_study_conductor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblestudy',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biblestudyinfo',
            name='living_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.biblestudy'),
        ),
        migrations.AlterField(
            model_name='livingtalkinfo',
            name='living_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.livingtalk'),
        ),
    ]
