# Generated by Django 5.1.7 on 2025-04-01 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_role_dutyassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyassignment',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.role'),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='assigned_duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.assignedduties'),
        ),
    ]
