# Generated by Django 5.1.7 on 2025-04-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_assignedduties_alter_dutyassignment_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='dutyassignment',
            name='role',
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.duty'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
