# Generated by Django 5.1.7 on 2025-04-02 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_duty_remove_dutyassignment_role_dutyassignment_duty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='assignedduties',
            name='type',
            field=models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister')], default='Brother', max_length=10),
        ),
        migrations.CreateModel(
            name='PublicTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=225)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.assignedpublic')),
            ],
        ),
        migrations.CreateModel(
            name='WatchtowerStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.assignedpublic')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.assignedduties')),
            ],
        ),
        migrations.CreateModel(
            name='SundaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closing_prayer', models.CharField(max_length=255, null=True)),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.assignedduties')),
                ('public_discourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.publictalk')),
                ('watchtower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.watchtowerstudy')),
            ],
        ),
    ]
