# Generated by Django 5.1.7 on 2025-04-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_assignedpart_assignedpublic_assignedduties_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayschedule',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
