# Generated by Django 5.1.7 on 2025-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_alter_sundayschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedduties',
            name='type',
            field=models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Appointed Brother', 'apponinted_brother')], default='Brother', max_length=100),
        ),
    ]
