# Generated by Django 5.1.7 on 2025-04-02 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_delete_assignedpart_alter_publictalk_speaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayschedule',
            name='closing_prayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_prayer', to='schedule.assignedduties'),
        ),
    ]
