# Generated by Django 5.1.7 on 2025-04-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_alter_sundayschedule_closing_prayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApponitedBrother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Austin Maturure', max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='publictalk',
            name='speaker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule.apponitedbrother'),
        ),
        migrations.AlterField(
            model_name='sundayschedule',
            name='chairman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.apponitedbrother'),
        ),
        migrations.AlterField(
            model_name='watchtowerstudy',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.apponitedbrother'),
        ),
    ]
