# Generated by Django 5.1.7 on 2025-04-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_apponitedbrother_alter_publictalk_speaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apponitedbrother',
            name='full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.assignedduties'),
        ),
    ]
