# Generated by Django 5.1.7 on 2025-04-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_alter_apponitedbrother_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apponitedbrother',
            old_name='full_name',
            new_name='brother',
        ),
    ]
