# Generated by Django 5.1.7 on 2025-04-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_dutyassignment_sundayschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayDutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_duty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.assignedduties')),
                ('duty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.duty')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.sundayschedule')),
            ],
        ),
    ]
