# Generated by Django 5.1.7 on 2025-04-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0030_sundaydutyassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyassignment',
            name='sundayschedule',
        ),
    ]
