# Generated by Django 5.1.7 on 2025-05-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_remove_dutyassignment_sundayschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesource',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
